config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # get 'smoothies', to: 'pages#smoothies'
  get 'contact', to: 'pages#contact'
  get 'faqs', to: 'pages#faqs'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'newsletter', to: 'pages#newsletter'
  get 'customer/choose_standard', to: 'customers#choose_standard', as: :choose_standard
  get 'customer/choose_custom', to: 'customers#choose_custom', as: :choose_custom
  get 'smoothies/:id', to: "smoothies#show", as: :smothie_page
  patch 'add_to_basket', to: 'baskets#add_to_basket', as: :add_to_basket
  patch 'update_newsletter', to: 'users#update_newsletter', as: :update_newsletter
  get 'my_nutrition/:basket_id', to: 'baskets#my_nutrition', as: :my_nutrition
  get 'update_subscription/:id', to: 'customers#update_subscription', as: :update_subscription
  get 'customers/:id/dashboard_edit', to: "customers#dashboard_edit", as: :dashboard_edit
  patch 'customers/:id/dashboard_update', to: "customers#dashboard_update", as: :dashboard_update
  get 'customers/:id/update_status', to: "customers#update_status", as: :update_status
  get 'blog', to: 'articles#index'
  get 'about', to: 'pages#about'
# basket - customers/:customer_id/baskets/:basket_id

  resources :articles, only: [:create, :new, :edit, :update]
  resources :users do
    get :postcode_checker, on: :member
    patch :postcode_result, on: :member
  end

  resources :customers do
    resources :baskets do
      patch :cancel_subscription, on: :member
      patch :pause_subscription, on: :member
    end
    resources :addresses
    resources :payments, only: [:new, :create]
  end

  get 'blog/:slug', to: "articles#show", as: :article_page

  resources :smoothies

  resources :newsletter_subscribers, only: [:create, :new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice.html_safe %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert.html_safe %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
	<div class="footer-logo">
		<%= image_tag "logo.png" %>
	</div>
	<div class="footer-column footer-left">
		<%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works") %>
		<%= link_to "What Is Yoggie?", root_path(:anchor => "about-yoggies") %>
		<%= link_to "Contact Us", contact_path %>
		<%= link_to "Blog", blog_path %>
	</div>
	<div class="footer-column footer-center">
		<%= link_to "FAQs", faqs_path %>
		<%= link_to "Privacy", privacy_path %>
		<%= link_to "Terms", terms_path %>
		<%= link_to "Website by MouseCode", "http://www.mouse-code.com", target: "_blank" %>
	</div>
	<div class="footer-column footer-right">
		<div class="social-footer">
			<%= link_to "https://www.facebook.com/YoggieSmoothies", target: "_blank" do %>
      			<i class="fa fa-facebook"></i>
    		<% end %>
    		<%= link_to "https://twitter.com/YoggieSmoothies", target: "_blank" do %>
      			<i class="fa fa-twitter"></i>
   			<% end %>
    		<%= link_to "https://www.instagram.com/yoggiesmoothies/", target: "_blank" do %>
      			<i class="fa fa-instagram"></i>
    		<% end %>
    	</div>
		<p>Copyright © <%= Date.today.year %> Yoggie</p>
	</div>
</div>

app/views/shared/_navbar-main.html.erb
<div class="navbar-yoggie-main">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-yoggie-brand-main" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <div class="main-nav hidden-xs hidden-sm">
    <%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works"), class: "navbar-yoggie-link" %>
    <%= link_to "What is Yoggie?", root_path(:anchor => "about-yoggies"), class: "navbar-yoggie-link"  %>
    <%= link_to "Our Yoggies",  smoothies_path, class: "navbar-yoggie-link"  %>
  </div>

  <% unless current_user&.customer&.basket %>
    <%= link_to "CREATE MY TAILORED YOGGIE", choose_custom_path, class: 'btn-navbar-scroll' %>
  <% end %>

<div class="navbar-yoggie-login-main">
  <% if current_user %>
    <% if current_user.customer %>
      <%= link_to customer_path(current_user.customer) do %>
        <i class="fa fa-user icon-pink"></i>
      <%end%>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete  do %>
      <i class="fa fa-sign-out icon-pink"></i>
    <%end%>
  <% else %>
    <%= link_to new_user_session_path do %>
      <i class="fa fa-user icon-pink"></i>
    <%end%>
  <% end %>
  <div class="navbar-yoggie-social">
    <%= link_to "https://www.facebook.com/YoggieSmoothies", target: "_blank" do %>
      <i class="fa fa-facebook"></i>
    <% end %>
    <%= link_to "https://twitter.com/YoggieSmoothies", target: "_blank" do %>
      <i class="fa fa-twitter"></i>
    <% end %>
    <%= link_to "https://www.instagram.com/yoggiesmoothies/", target: "_blank" do %>
      <i class="fa fa-instagram"></i>
    <% end %>
  </div>
</div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-yoggie-item hidden-md hidden-lg">
    <div class="dropdown dropdown-main">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-yoggie-dropdown-menu">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works") %></li>
        <li><%= link_to "What is Yoggie?", root_path(:anchor => "about-yoggies") %></li>
        <li><%= link_to "Our Yoggies", smoothies_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-yoggie">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-yoggie-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <div class="main-nav hidden-xs hidden-sm">
    <%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works"), class: "navbar-yoggie-link", id: "how-it-worksl" %>
    <%= link_to "What is Yoggie?", root_path(:anchor => "about"), class: "navbar-yoggie-link", id: "about-yoggies"  %>
    <%= link_to "Our Yoggies", smoothies_path, class: "navbar-yoggie-link", id: "pick-plan-section1" %>
  </div>

  <div class="navbar-yoggie-top-nav">
    <div class="top-nav-links">
      <% if current_user %>
        <%= link_to 'My Dashboard', customer_path(current_user.customer) if current_user.customer %>
        <div class="top-nav-line"></div>
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Log In', new_user_session_path %>
        <div class="top-nav-line"></div>
        <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>
      <div class="navbar-yoggie-social">
      <%= link_to "https://www.facebook.com/YoggieSmoothies", target: "_blank" do %>
        <i class="fa fa-facebook"></i>
      <% end %>
      <%= link_to "https://twitter.com/YoggieSmoothies", target: "_blank" do %>
        <i class="fa fa-twitter"></i>
      <% end %>
      <%= link_to "https://www.instagram.com/yoggiesmoothies/", target: "_blank" do %>
        <i class="fa fa-instagram"></i>
      <% end %>
    </div>
  </div>
  </div>



  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-yoggie-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-yoggie-dropdown-menu">
        <li><%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works") %></li>
        <li><%= link_to "What is Yoggie?", root_path(:anchor => "about-yoggies") %></li>
        <li><%= link_to "Our Yoggies", smoothies_path %></li>
      </ul>
    </div>
  </div>
</div>


<!-- on landing scroll only -->

<div class="navbar-yoggie-scroll hidden slideRight">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-yoggie-brand-scroll" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <div class="main-nav hidden-xs ">
    <%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works"), class: "navbar-yoggie-link", id: "how-it-works1" %>
    <%= link_to "What is Yoggie?", root_path(:anchor => "about"), class: "navbar-yoggie-link", id: "about-yoggies1"  %>
    <%= link_to "Our Yoggies", smoothies_path, class: "navbar-yoggie-link", id: "pick-plan-section2" %>
  </div>

  <%= link_to "CREATE MY TAILORED YOGGIE", new_customer_path, class: 'btn-navbar-scroll' %>

<div class="navbar-yoggie-login-scroll">
  <% if current_user %>
    <% if current_user.customer %>
      <%= link_to customer_path(current_user.customer) do %>
        <i class="fa fa-user icon-pink"></i>
      <%end%>
    <% end %>
    <%= link_to destroy_user_session_path, method: :delete  do %>
      <i class="fa fa-sign-out icon-pink"></i>
    <%end%>
  <% else %>
    <%= link_to new_user_session_path do %>
      <i class="fa fa-user icon-pink"></i>
    <%end%>
  <% end %>
  <div class="navbar-yoggie-social">
    <%= link_to "https://www.facebook.com/yoggie", target: "_blank" do %>
          <i class="fa fa-facebook"></i>
        <% end %>
        <%= link_to "https://twitter.com/yoggie", target: "_blank" do %>
          <i class="fa fa-twitter"></i>
        <% end %>
        <%= link_to "https://www.instagram.com/yoggie/", target: "_blank" do %>
          <i class="fa fa-instagram"></i>
        <% end %>
    </div>
</div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-yoggie-item hidden-sm hidden-md hidden-lg">
    <div class="dropdown dropdown-scroll">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-yoggie-dropdown-menu">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "How Yoggie Works", root_path(:anchor => "how-it-works") %></li>
        <li><%= link_to "What is Yoggie?", root_path(:anchor => "about-yoggies") %></li>
        <li><%= link_to "Our Yoggies", smoothies_path %></li>
      </ul>
    </div>
  </div>
</div>