config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # get 'smoothies', to: 'pages#smoothies'
  get 'contact', to: 'pages#contact'
  get 'faqs', to: 'pages#faqs'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'newsletter', to: 'pages#newsletter'
  get 'customer/choose_standard', to: 'customers#choose_standard', as: :choose_standard
  get 'customer/choose_custom', to: 'customers#choose_custom', as: :choose_custom
  get 'smoothies/:id', to: "smoothies#show", as: :smothie_page
  patch 'add_to_basket', to: 'baskets#add_to_basket', as: :add_to_basket
  patch 'update_newsletter', to: 'users#update_newsletter', as: :update_newsletter
  get 'my_nutrition/:basket_id', to: 'baskets#my_nutrition', as: :my_nutrition
  get 'update_subscription/:id', to: 'customers#update_subscription', as: :update_subscription
  get 'customers/:id/dashboard_edit', to: "customers#dashboard_edit", as: :dashboard_edit
  patch 'customers/:id/dashboard_update', to: "customers#dashboard_update", as: :dashboard_update
  get 'customers/:id/update_status', to: "customers#update_status", as: :update_status
  get 'blog', to: 'articles#index'
  get 'about', to: 'pages#about'
# basket - customers/:customer_id/baskets/:basket_id

  resources :articles, only: [:create, :new, :edit, :update]
  resources :users do
    get :postcode_checker, on: :member
    patch :postcode_result, on: :member
  end

  resources :customers do
    resources :baskets do
      patch :cancel_subscription, on: :member
      patch :pause_subscription, on: :member
    end
    resources :addresses
    resources :payments, only: [:new, :create]
  end

  get 'blog/:slug', to: "articles#show", as: :article_page

  resources :smoothies

  resources :newsletter_subscribers, only: [:create, :new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/models/customer.rb
class Customer < ApplicationRecord
  belongs_to :user
  has_one :basket
  has_one :address
  extend FriendlyId
  friendly_id :slug, use: :slugged
  # validates_presence_of :first_name, :last_name, :age, :gender, :activity_level
  # validates_presence_of :goal, :height, :weight

  accepts_nested_attributes_for :address

  ACTIVITY_LEVEL_MULTIPLIERS = {
    'Sedentary' => 1.1,
    'Lightly Active' => 1.2,
    'Moderately Active' => 1.35,
    'Super Active' => 1.45
  }.freeze

  GOAL_MULTIPLIERS = {
    'Lose Fat' => 0.8,
    'Health Boost' => 1,
    'Gain Muscle' => 1.1
  }.freeze

  MEALS_PER_DAY = {
    '3 or less' => 3,
    '4' => 4,
    '5 or more' => 5
  }

  GENDER = ['Guy', 'Girl'].freeze

  def full_name
    arr = [first_name, last_name].reject { |n| n.blank? }
    arr.join(' ')
  end

  def calculate_stats
    update(
      bmr: calculate_bmr,
      tdee: calculate_TDEE,
      daily_calorie_goal: calculate_daily_calories,
      calories_per_shake: calculate_shake_calories,
      protein: calculate_protein,
      fat: calculate_fat,
      carbs: calculate_carbs
      )
    user.update(standard: false)
  end

  def calculate_bmr
    BMRCalculator.new(self).calculate
  end

  def calculate_TDEE
    calculate_bmr * ACTIVITY_LEVEL_MULTIPLIERS[activity_level]
  end

  def calculate_daily_calories
    calculate_TDEE * GOAL_MULTIPLIERS[goal]
  end

  def calculate_shake_calories
    calculate_daily_calories / meals_per_day
  end

  def calculate_protein
    ProteinCalculator.new(self).percent_protein
  end

  def calculate_fat
    FatCalculator.new(self).percent_fat
  end

  def calculate_carbs
    100 - calculate_protein - calculate_fat
  end

  def standard?
    user.standard
  end

  def tailored?
    !user.standard
  end

  def check_status
    if !basket.nil?
      return if !basket.tailored? && standard?
      return if basket.tailored? && tailored?
      update_user_status
    end
  end

  def update_user_status
    user.update(standard: current_standard_status)
  end

  def current_standard_status
   user.standard ? true : false
  end

  def calculate_tailored_stat(smoothie, stat_symbol)
    # stat symbol can be any value in NutriInfo for the Smoothie
    original_stat = smoothie.nutri_info[stat_symbol]

    multiplication_factor = (calories_per_shake / smoothie.nutri_info[:energy_kcal])

    tailored_stat = (original_stat * multiplication_factor).round(1)

    # convert to integer if zero value at decimal places
    tailored_stat % 1 == 0 ? tailored_stat.to_i : tailored_stat
  end

  def generate_order_csv
    smoothie_group = basket&.smoothies&.first&.group&.name
    smoothie_size = basket&.smoothies&.first&.size&.name

    CSV.generate do |csv|
       csv << ["CUSTOMER DETAILS", ""]
       csv << ["CustomerRef", slug]
       csv << ["FirstName", first_name]
       csv << ["LastName", last_name]
       csv << ["AddressLine1", address&.address_line_one]
       csv << ["AddressLine2", address&.address_line_two]
       csv << ["AddressLine3", address&.address_line_three]
       csv << ["Postcode", address&.postcode]
       csv << ["SafePlace", address&.delivery_instructions]
       csv << ["MACROS", ""]
       csv << ["kCal", calories_per_shake]
       csv << ["protein", protein]
       csv << ["carbs", carbs]
       csv << ["fats", fat]
       csv << ["CUSTOMISATION QUESTIONS", ""]
       csv << ["Sex", gender]
       csv << ["Weight_kg", weight]
       csv << ["Height_cm", height]
       csv << ["Age", age]
       csv << ["ActivityLevel", activity_level]
       csv << ["Goal", goal]
       csv << ["MealsPerDay", meals_per_day]
       csv << ["ORDER DETAILS", ""]
       csv << ["OrderRef", basket&.stripe_sub_id]
       csv << ["OrderDate", "#{Date.today.day.ordinalize} #{Date.today.strftime("%B, %Y")}"]
       csv << ["DeliveryDate", basket&.next_delivery_date_string]
       csv << ["OrderType", "#{standard? ? 'STANDARD' : 'TAILORED'}"]
       csv << ["Group", smoothie_group]
       csv << ["Size", smoothie_size]
       csv << ["Smoothie1", basket&.smoothies[0]&.name&.titleize]
       csv << ["Smoothie2", basket&.smoothies[1]&.name&.titleize]
       csv << ["Smoothie3", basket&.smoothies[2]&.name&.titleize]
       csv << ["Smoothie4", basket&.smoothies[3]&.name&.titleize]
       csv << ["Smoothie5", basket&.smoothies[4]&.name&.titleize]
    end
  end

  private

  def should_generate_new_friendly_id?
    self.slug.nil?
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:edit, :update, :show, :update_subscription, :dashboard_edit, :dashboard_update, :update_status]
  skip_before_action :authenticate_user!, only:[:choose_standard, :choose_custom]

  def new
    if current_user.customer && !current_user.standard
      if current_user.customer.basket.nil?
        @basket = Basket.create(customer: current_user.customer)
      end
      redirect_to edit_customer_path(current_user.customer)
    else
      if current_user.valid_postcode?
        @customer = Customer.create(user_id: current_user.id)
        if @customer.basket.nil?
          @basket = Basket.create(customer: current_user.customer)
        end

      else
        redirect_to postcode_checker_user_path(current_user)
      end
    end
  end

  def create
    @customer = Customer.new(customer_params)
    @customer.user = current_user
    if @customer.save
      @customer.calculate_stats if !@customer.standard?
      redirect_to new_customer_basket_path(@customer)
    else
      render :new
    end
  end

  def show
    if @customer.basket
      @customer.check_status
      @basket = @customer.basket
      @status = determine_status
      @sub_status = correct_subscription?
    else
      @basket = Basket.create(customer: current_user.customer)
    end

    @next_delivery_date_string = @basket.next_delivery_date_string
  end


  def edit
  end

  def update
    @customer.update(customer_params)

    if @customer.standard? && @customer.address.nil?
      if @customer.basket && @customer.basket.full?
        redirect_to new_customer_address_path(current_user.customer)
      else
        redirect_to smoothies_path
      end
    elsif @customer.basket && @customer.basket.full?
      @customer.calculate_stats if !@customer.standard?
      redirect_to new_customer_payment_path(@customer)
    elsif !@customer.standard?
      @customer.calculate_stats
      redirect_to smoothies_path
    else
      redirect_to smoothies_path
    end
  end


  def update_subscription
    basket = @customer.basket

    if @customer.user.standard
      @customer.user.update(standard: params[:standard])
      # Change to tailored
      if basket
        # reset smoothies to proper group and size
        smoothie_names = basket.smoothies.pluck(:name)
        basket.smoothies.destroy_all
        smoothie_names.each do |smoothie_name|
          standard_smoothie = Smoothie.fetch_bundle(@customer).find_by(name: smoothie_name)
          basket.smoothies << standard_smoothie if standard_smoothie
        end
      end
      AdminMailer.subscription_change(@customer).deliver_now if @customer.basket.active?
      redirect_to edit_customer_path(@customer)
    else
      @customer.user.update(standard: params[:standard])
      # Change to standard
      if basket
        # reset smoothies to standard
        smoothie_names = basket.smoothies.pluck(:name)
        basket.smoothies.destroy_all
        smoothie_names.each do |smoothie_name|
          standard_smoothie = Smoothie.standard.find_by(name: smoothie_name)
          basket.smoothies << standard_smoothie if standard_smoothie
        end
      end
      AdminMailer.subscription_change(@customer).deliver_now if @customer.basket.active?
      redirect_to smoothies_path(@customer)
    end
  end

  def dashboard_edit
  end


  def dashboard_update
    original_customer_updated_at = @customer.updated_at

    if @customer.update(customer_params)
      @customer.calculate_stats if !@customer.standard?

      if @customer.basket&.active? && @customer.updated_at != original_customer_updated_at
        # Send order changed emails if attributes changed
        AdminMailer.subscription_change(@customer).deliver_now
      end

      redirect_to customer_path(@customer)
    else
      render :edit
    end
  end


  def choose_standard
    if user_signed_in?
      current_user.standard = true
      @original_user_updated_at = current_user.updated_at
      current_user.save

      change_subscription_and_reset_smoothies
      flash[:notice] = "Successfully changed plan to standard"
      redirect_to smoothies_path
    else
      session[:standard] = true
      redirect_to new_user_registration_path
    end

  end

  def choose_custom
    if user_signed_in?
      current_user.standard = false
      @original_user_updated_at = current_user.updated_at
      current_user.save

      change_subscription_and_reset_smoothies
      flash[:notice] = "Successfully changed plan to tailored"
      redirect_to smoothies_path
    else
      session[:standard] = false
      redirect_to new_user_registration_path
    end
  end

  def update_status
    if current_user.basket.status == 'cancelled'
      current_user.basket.update(status: '')
      redirect_to smoothies_path
    end
  end

  private

  def determine_status
    return 'Cancelled' if @customer.basket.status == 'cancelled'
    return 'Standard' if @customer.standard?
    return 'Tailored' if @customer.tailored?
  end

  def correct_subscription?
    return false unless @customer.basket&.stripe_sub_id
    subscription = Stripe::Subscription.retrieve(@customer&.basket&.stripe_sub_id)
    type = @customer&.basket&.tailored? ? :tailored : :standard
    subscription['plan']['amount'] == Basket::SUBSCRIPTION_FEE[type]
  end

  def set_customer
    @customer = Customer.friendly.find(params[:id])
  end

  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :weight, :height,
                                     :activity_level, :goal, :age, :gender,
                                     :newsletter, :email, :phone, :meals_per_day)
  end

  def change_subscription_and_reset_smoothies
    customer = current_user.customer
    basket = customer&.basket
    if current_user.standard?
      bundled_smoothies = Smoothie.standard
    else
      bundled_smoothies = Smoothie.fetch_bundle(customer)
    end

    original_basket_smoothies_ids = basket&.smoothies&.pluck(:id)
    if basket
      # reset smoothies to proper group and size
      smoothie_names = basket.smoothies.pluck(:name)
      basket.smoothies.destroy_all
      smoothie_names.each do |smoothie_name|
        standard_smoothie = bundled_smoothies.find_by(name: smoothie_name)
        basket.smoothies << standard_smoothie if standard_smoothie
      end

      if customer.basket.active? && @original_user_updated_at != current_user.updated_at && original_basket_smoothies_ids.sort != basket.smoothies.pluck(:id).sort
        AdminMailer.subscription_change(customer).deliver_now
        CustomerMailer.order_change(customer).deliver_now
      end
    end
  end
end

app/views/customers/create.html.erb
<h1>Customers#create</h1>
<p>Find me in app/views/customers/create.html.erb</p>

app/views/customers/dashboard_edit.html.erb
<%= render 'shared/flashes' %>
<div class="our-smoothies-banner"></div>
<div class="form-wrapper vitals-form">
  <h3 class="text-center">In 7 questions, we'll create your nutritionally perfect smoothie! Go...</h3>
  <br>

  <%= simple_form_for @customer, url: dashboard_update_path, method: :patch do |f| %>

    <%= f.input :first_name %>

    <%= f.input :last_name %>
    <%= f.input :gender, as: :select, collection: Customer::GENDER.map{|g|g.humanize}, required: true %>
    <%= f.input :age , required: true%>
    <%= f.input :height, label: 'Height (cm)', required: true %>
    <%= f.input :weight, label: 'Weight (kg)' , required: true%>
    <%= f.input :meals_per_day, as: :select, collection: Customer::MEALS_PER_DAY, required: true  %>
    <%= f.input :activity_level, as: :select, collection: Customer::ACTIVITY_LEVEL_MULTIPLIERS.keys, required: true %>
    <%= f.input :goal, as: :select, collection: Customer::GOAL_MULTIPLIERS.keys, required: true %>
    <div class="results-button">
      <%= f.submit 'GET MY RESULTS', class: "btn-yoggie-main-green text-center" %>
      <% end %>
    </div>
</div>

app/views/customers/edit.html.erb
<%= render 'shared/flashes' %>
<div class="our-smoothies-banner"></div>
<div class="form-wrapper vitals-form">
  <h3 class="text-center">In 7 questions, we'll create your nutritionally perfect smoothie! Go...</h3>
  <br>

  <%= simple_form_for @customer do |f| %>

    <%= f.input :first_name %>

    <%= f.input :last_name %>
    <%= f.input :gender, label:'I am a...',  as: :select, collection: Customer::GENDER.map{|g|g.humanize}, required: true %>
    <%= f.input :age , required: true%>
    <%= f.input :height, label: 'Height (cm)', required: true %>
    <%= f.input :weight, label: 'Weight (kg)' , required: true%>
    <%= f.input :meals_per_day, as: :select, collection: Customer::MEALS_PER_DAY.keys, required: true  %>
    <%= f.input :activity_level, as: :select, collection: Customer::ACTIVITY_LEVEL_MULTIPLIERS.keys, required: true %>
    <%= f.input :goal, as: :select, collection: Customer::GOAL_MULTIPLIERS.keys, required: true %>
    <div class="results-button">
      <%= f.submit 'GET MY RESULTS', class: "btn-yoggie-main-green text-center" %>
      <% end %>
    </div>
</div>

app/views/customers/new.html.erb
<div class="our-smoothies-banner"></div>
<div class="form-wrapper">
  <% if !current_user.standard %>
    <h3 class="text-center" style="padding-bottom: 20px;">In 7 questions, we'll create your nutritionally perfect smoothie! Go...</h3>
  <% else %>
    <div class="yoggie-form-link">
      <%= link_to 'Prefer to choose from our Tailored Yoggies? Click here...', user_path(current_user, user: { standard: false }), method: :patch, remote: true %>
    </div>
    <h3 class="text-center" style="padding-bottom: 20px;">Please fill out your customer information</h3>
  <% end %>
  <%= simple_form_for @customer do |f| %>
    <%= f.input :first_name %>
    <!-- <%= f.input :last_name %> -->
    <%= f.input :gender, as: :select, collection: Customer::GENDER.map{|g|g.humanize} %>
    <%= f.input :age %>
    <% if !current_user.standard %>
      <%= f.input :height, label: 'Height (cm)' %>
      <%= f.input :weight, label: 'Weight (kg)' %>
      <%= f.input :meals_per_day, as: :select, collection: Customer::MEALS_PER_DAY.keys  %>
      <%= f.input :activity_level, as: :select, collection: Customer::ACTIVITY_LEVEL_MULTIPLIERS.keys %>
      <%= f.input :goal, as: :select, collection: Customer::GOAL_MULTIPLIERS.keys %>
      <%= f.submit 'GET MY RESULTS', class: "btn-yoggie-main-green text-center" %>
    <% else %>
      <!-- <%= link_to 'Want smoothies tailored to your needs? Click here', user_path(current_user, user: { standard: false }), method: :patch, remote: true %> -->
      <%= f.submit 'Submit', class: "btn-yoggie-main-green" %>
    <% end %>
  <% end %>
</div>

app/views/customers/show.html.erb
<%= render 'shared/flashes' %>
<div class="customer-vitals-wrapper">

	<div class="customer-vitals-box">
		<h2>My Dashboard</h2>
		<h3><%= @customer.first_name %> <%= @customer.last_name %></h3>
      <hr>
      <% if !@customer.standard? %>
      <div class="customer-vitals">
      <div class="customer-vitals-details">
        <h4>My info</h4>
        <p>Name: <span><%= @customer.first_name %></span></p>
        <p>Age: <span><%= @customer.age %></span></p>
        <p>I am a: <span><%= @customer.gender %></span></p>
        <p>My height is: <span><%= @customer.height %>cm</span></p>
        <p>I weigh: <span><%= @customer.weight %>kg</span></p>
        <p>I typically eat: <span><%= @customer.meals_per_day %> meals per day</span></p>
        <p>Activity level: <span><%= @customer.activity_level %></span></p>
        <p>My goal is to: <span><%= @customer.goal %></span></p>
        <%= link_to 'Change or add info', dashboard_edit_path(@customer) %>
      </div>

      <% if @customer.basket && !@customer.standard? %>
        <div class="customer-vitals-nutrition">
          <h4>My numbers</h4>
          <!--  -->
          <div class="macro-main left">
            <div class="macro-info-left">
              <div class="info-focus"><%= @customer.calories_per_shake %></div>
              <div>kcal per yoggie</div>
            </div>

            <ul class="macro-info-list">
              <li class="green-border">
                <div class="percentage"><%= @customer.protein %>%</div>
                <div class="nutri">Protein</div>
                <div class="grams half-circle"></div>
              </li>
              <li class="yellow-border">
                <div class="percentage"><%= @customer.carbs %>%</div>
                <div class="nutri">Carbs</div>
                <div class="grams half-circle"></div>
              </li>
              <li class="orange-border">
                <div class="percentage"><%= @customer.fat %>%</div>
                <div class="nutri">Fats</div>
                <div class="grams half-circle"></div>
              </li>
            </ul>
          </div>
          <!--  -->
          <br>
          <p>My BMR: <span><%= @customer.bmr %></span></p>
          <p>Total Daily Energy Expenditure: <span><%= @customer.tdee %></span></p>
          <p>Daily Target Caloric Intake: <span><%= @customer.daily_calorie_goal %></span></p>
          <% if @customer&.basket.active? %>
            <%= link_to 'Change to tailored smoothies', update_subscription_path(@customer, standard: false) if @customer.standard? %>
            <%= link_to 'Change to standard smoothies', update_subscription_path(@customer, standard: true) if !@customer.standard? %>
          <% end %>
        </div>
      </div>
    <% end %>
    <% end %></br>
      <div class="customer-vitals-subscription">
        <br>
        <h4>My account</h4>
        <h4 id="details-click" class="my-account-title"><%= link_to "Details:" %></h4>
        <div class="details" style="display: none;">
          <ul>
            <p>Name: <span><%= @customer.first_name %></span></p>
            <p>I am a: <span><%= @customer.gender %></span></p>
            <p>Email: <span><%= @customer.user.email %></span></p>
            <p>Address 1: <span><%= @customer.address&.address_line_one %></span></p>
            <p>Address 2: <span><%= @customer.address&.address_line_two %></span></p>
            <p>Address 3: <span><%= @customer.address&.address_line_three %></span></p>
            <p>Postcode: <span><%= @customer.address&.postcode %></span></p>
            <p>Delivery Instructions: <span>Safe Place:<%= @customer.address&.delivery_instructions %></span></p>
            <div class="change-my-yoggies">
            <%= link_to 'Change my address', edit_customer_address_path(@customer) %>
            </div>
          </ul><br>
        </div>

        <h4 id="next-box-click" class="my-account-title"><%= link_to "In my next box:" %></h4>
        <div class="next-box" style="display: none;">
          <p>I have a weekly subscription of...</p>
          <ul>
            <% if @customer.basket && @customer.basket.smoothies %>
             <% @customer.basket.smoothies.group_by {|smoothie| smoothie.name}.each do |smoothie_array| %>
                <p><span><%= smoothie_array[1].count %> x <%= smoothie_array[0].titleize %><span></p>
              <% end %>
          <% end %>
          </ul>
          <div class="change-my-yoggies">
            <%= link_to 'CHANGE MY YOGGIES', smoothies_path(@customer, @customer.basket), class: "btn-yoggie-main-clear" %>
          </div><br>
          <%= link_to "Pay for my Yoggies",edit_customer_path(current_user.customer) if @customer&.basket.status == 'pending' && @basket.smoothies.count == 5  %>
          <% if @customer&.basket.active? %>
            <% unless @sub_status %>
              <p>Your subscription needs updating: <%= link_to 'Click here to update', new_customer_payment_path(@customer) %></p>
            <% end %>
            <%= link_to 'Cancel My Subscription', cancel_subscription_customer_basket_path(@customer, @customer.basket), method: :patch if @basket.active? %>
            <%= link_to 'My nutrition section', my_nutrition_path(@customer.basket) %>
          <% end %><br>
        <br>
        </div>

        <h4 id="delivery-click" class="my-account-title"><%= link_to "Delivery:" %></h4>
        <div class="delivery" style="display: none;">
          <p>Delivery day: <span>Tuesday</span></p>
          <p>Delivery time: <span>0300 - 0600</span></p>
          <br>
        </div>

        <h4 id="order2-click" class="my-account-title"><%= link_to "Order:" %></h4>
        <div class="order2" style="display: none;">
          <p>Plan: <span><%= @status %></span></p>
          <p>Next delivery: <span><%= @next_delivery_date_string %></span></p>
          <div class="change-my-yoggies">
            <%= link_to 'Pause My Subscription', pause_subscription_customer_basket_path(@customer, @customer.basket), method: :patch if @basket.active? %>
          </div>
          <% unless @customer&.basket&.status == 'cancelled' %>
            <% if @customer.tailored? %>
              <%= link_to 'Change my plan to standard', choose_standard_path %>
            <% elsif @customer.standard? %>
              <%= link_to 'Change my plan to tailored', choose_custom_path %>
            <% end %>
          <% end %>
        </div>
    <br>
	</div>
</div>

app/views/customers/update.html.erb
<h1>Customers#update</h1>
<p>Find me in app/views/customers/update.html.erb</p>