config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # get 'smoothies', to: 'pages#smoothies'
  get 'contact', to: 'pages#contact'
  get 'faqs', to: 'pages#faqs'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'newsletter', to: 'pages#newsletter'
  get 'customer/choose_standard', to: 'customers#choose_standard', as: :choose_standard
  get 'customer/choose_custom', to: 'customers#choose_custom', as: :choose_custom
  get 'smoothies/:id', to: "smoothies#show", as: :smothie_page
  patch 'add_to_basket', to: 'baskets#add_to_basket', as: :add_to_basket
  patch 'update_newsletter', to: 'users#update_newsletter', as: :update_newsletter
  get 'my_nutrition/:basket_id', to: 'baskets#my_nutrition', as: :my_nutrition
  get 'update_subscription/:id', to: 'customers#update_subscription', as: :update_subscription
  get 'customers/:id/dashboard_edit', to: "customers#dashboard_edit", as: :dashboard_edit
  patch 'customers/:id/dashboard_update', to: "customers#dashboard_update", as: :dashboard_update
  get 'customers/:id/update_status', to: "customers#update_status", as: :update_status
  get 'blog', to: 'articles#index'
  get 'about', to: 'pages#about'
# basket - customers/:customer_id/baskets/:basket_id

  resources :articles, only: [:create, :new, :edit, :update]
  resources :users do
    get :postcode_checker, on: :member
    patch :postcode_result, on: :member
  end

  resources :customers do
    resources :baskets do
      patch :cancel_subscription, on: :member
      patch :pause_subscription, on: :member
    end
    resources :addresses
    resources :payments, only: [:new, :create]
  end

  get 'blog/:slug', to: "articles#show", as: :article_page

  resources :smoothies

  resources :newsletter_subscribers, only: [:create, :new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/controllers/smoothies_controller.rb
class SmoothiesController < ApplicationController
  skip_before_action :authenticate_user!

  def index
    @smoothies = Smoothie.standard
    if user_signed_in? && current_user.customer.basket.nil?
      @basket = Basket.create(customer: current_user.customer)
    end
    if user_signed_in? && current_user.customer.tailored?
      if current_user.customer.protein.nil?
        redirect_to edit_customer_path(current_user.customer)
      else
        @smoothies = Smoothie.fetch_bundle(current_user.customer)
      end
    else
    end
  end

  def show
    @smoothie = Smoothie.all.find {|a| a.slug == params[:id]}
    @smoothie = Smoothie.all.find(params[:id]) if @smoothie == nil
    @basket = BasketSmoothie.new
    @badges = @smoothie.badges

    @small_ingredients = Ingredient.joins(:smoothie_ingredients)
      .where(smoothie_ingredients: {smoothie: @smoothie, large: false},
             superfood: nil).uniq

    @large_ingredients = Ingredient.joins(:smoothie_ingredients)
      .where(smoothie_ingredients: {smoothie: @smoothie, large: true},
             superfood: nil).uniq

    @special_ingredients = Ingredient.joins(:smoothie_ingredients)
      .where(smoothie_ingredients: {smoothie: @smoothie}).where(special: true).uniq
  end
end

app/views/smoothies/_card.html.erb
  <div class="standard-yoggie <%= "active" if BasketSmoothie.where(smoothie: smoothie, basket: current_user.customer.basket).count >= 1 %>">
    <%= link_to smoothie_path(smoothie.slug) do %>
    <%= image_tag "https://res.cloudinary.com/dehjqm9b4/image/upload/v1568376288/Bare_hbplfq.png", class: 'bare-general' %>
    <%= cl_image_tag smoothie.image %>
    <% if user_signed_in? %>
    <div class="standard-yoggie-content">
    <% else %>
      <div class="standard-yoggie-content">
    <% end %>
       <h3><%= smoothie.name.titleize %><br></br></h3>
      <% end %>
      <% if current_user %>
        <%#= link_to "ADD TO BOX", new_customer_basket_path(current_user.customer), class: 'btn-yoggie-main-clear' %>
        <%= form_for [current_user.customer, current_user.customer.basket], :url => url_for(:controller => 'baskets', :action => 'add_to_basket') do |f| %>
          <%= hidden_field_tag 'customer_id', current_user.customer.id %>
          <%= hidden_field_tag 'smoothie_id', smoothie.id %>
          <div class="quantity-tag">
            <%= select_tag "quantity", options_for_select([0, 1, 2, 3, 4, 5], BasketSmoothie.where(smoothie: smoothie, basket: current_user.customer.basket).count) %>
          </div>
          <%#= link_to "ADD TO BOX", new_customer_path, class: 'btn-yoggie-main-clear' %>
          <div class="flex">
            <%= f.submit 'UPDATE BOX', class: "btn-yoggie-main-green "%>
          </div>
          <% end %>
        <% else %>
        <%= link_to 'UPDATE BOX', class: "btn-yoggie-main-green "%>
        <%= link_to " VIEW YOGGIE", smoothie_path(smoothie.slug), class: 'btn-yoggie-main-clear' %>
      <% end %>

      <p class="card-hover">
        <% smoothie.ingredients.each do |ingredient| %>
          ✓ &nbsp;<%= ingredient.name.titleize %></br>
        <% end %>
      </p>
    </div>
  </div>

app/views/smoothies/_card_guest.html.erb
<div class="standard-yoggie">
  <%= link_to smoothie_path(smoothie.slug) do %>
  <%= image_tag "https://res.cloudinary.com/dehjqm9b4/image/upload/v1568376288/Bare_hbplfq.png", class: 'bare-general' %>
  <%= cl_image_tag smoothie.image %>
  <div class="standard-yoggie-content ">
          <h3><%= smoothie.name.titleize %><br></br></h3><% end %>
        <%= link_to 'UPDATE BOX', new_user_session_path, class: "btn-yoggie-main-green text-center"%>
      <p class="card-hover">
        <% smoothie.ingredients.uniq.each do |ingredient| %>
          ✓ &nbsp;<%= ingredient.name.titleize %></br>
        <% end %>
      </p>
  </div>
</div>

app/views/smoothies/_card_tailored.html.erb
<div class="results-wrapper">
  <% unless current_user.customer.standard? %>
    <h4 class="text-center">Your perfect breakfast looks like this:</h4>
    <div class="results-content">
      <!--  -->
      <div class="macro-main left">
        <div class="macro-info-left">
          <div class="info-focus"><%= current_user.customer.calories_per_shake %></div>
          <div>kcal per yoggie</div>
        </div>

        <ul class="macro-info-list">
          <li class="green-border">
            <div class="percentage"><%= current_user.customer.protein %>%</div>
            <div class="nutri">Protein</div>
            <div class="grams half-circle"></div>
          </li>
          <li class="yellow-border">
            <div class="percentage"><%= current_user.customer.carbs %>%</div>
            <div class="nutri">Carbs</div>
            <div class="grams half-circle"></div>
          </li>
          <li class="orange-border">
            <div class="percentage"><%= current_user.customer.fat %>%</div>
            <div class="nutri">Fats</div>
            <div class="grams half-circle"></div>
          </li>
        </ul>
      </div>
      <!--  -->
      <br>
      <p><span>Your BMR: </span><span class="your-results"><%= current_user.customer.bmr %></span></p>
      <p><span>Your Total Daily Energy Expenditure: </span><span class="your-results"><%=current_user.customer.tdee %></span></p>
      <p><span>Daily Target Caloric Intake: </span><span class="your-results"><%= current_user.customer.daily_calorie_goal %> CAL</span></p>
      <%= link_to "Change my numbers", edit_customer_path(current_user.customer), class: "yoggie-standard-link" %>
    </div>
    <div class="results-line"></div>
    <% end %>
    <p class="results-text text-center">Pick your week’s <span>5</span> smoothie breakfasts below. We'll tweak each recipe to match the above. No worries, no fuss.</p>
    <% if @message %>
      <p style="color: red;"><%= @message %></p>
    <% end %>
</div>
    <div class="our-smoothies">
      <% smoothies.each do |smoothie| %>
      <%= image_tag "https://res.cloudinary.com/dehjqm9b4/image/upload/v1568376288/Bare_hbplfq.png", class: 'bare-general' %>
      <%= link_to smoothie_path(smoothie.slug) do %>
      <div class="standard-yoggie <%= "active" if BasketSmoothie.where(smoothie: smoothie, basket: current_user.customer.basket).count >= 1 %>">

        <%= cl_image_tag smoothie.image %>
        <div class="standard-yoggie-content">
            <h3><%= smoothie.name.titleize %><br></br></h3><% end %>
          <% if current_user %>
            <%#= link_to "ADD TO BOX", new_customer_basket_path(current_user.customer), class: 'btn-yoggie-main-clear' %>
            <%= form_for [current_user.customer, current_user.customer.basket], :url => url_for(:controller => 'baskets', :action => 'add_to_basket') do |f| %>
              <%= hidden_field_tag 'customer_id', current_user.customer.id %>
              <%= hidden_field_tag 'smoothie_id', smoothie.id %>
              <%= f.hidden_field :tailored, value: false if current_user.customer.standard? %>
              <%= f.hidden_field :tailored, value: true if current_user.customer.tailored? %>
              <%= select_tag "quantity", options_for_select([0, 1, 2, 3, 4, 5], BasketSmoothie.where(smoothie: smoothie, basket: current_user.customer.basket).count) %>
            <div class="flex">
              <%= f.submit 'UPDATE BOX', class: "btn-yoggie-main-green text-center"  %>
            </div>
          <% end %>
        <% else %>
        <%= link_to "VIEW YOGGIE", smoothie_path(smoothie.slug), class: 'btn-yoggie-main-clear text-center' %>
        <% end %>
          <p class="card-hover">
            <% smoothie.ingredients.uniq.each do |ingredient| %>
              ✓ &nbsp;<%= ingredient.name.titleize %></br>
            <% end %>
          </p>
        </div>
      </div>
      <% end %>
    </div>
  </div>

app/views/smoothies/index.html.erb
<%= render 'shared/flashes' %>
<div class="banner-padding"></div>
<% if user_signed_in? && current_user.customer.basket.smoothies.count == 5 %>
  <div class="banner-padding"></div>
<% else %>
<!-- <div class="our-smoothies-banner"></div> -->
<div class="banner-padding"></div>
<% end %>
<div class="our-smoothies-intro section-padding text-center">
	<br></br>
  <% if current_user&.customer&.first_name&.present? %>
    <h2><%= current_user.customer.first_name %>'s Yoggies</h2>
  <% else %>
	  <h2>Choose Your Yoggies</h2>
  <% end %>
	<br>
</div>
<div class="text-center">
  <% if user_signed_in? %>
    <% if current_user.customer.standard? %>
      <% if current_user.customer.basket.status == 'pending' && current_user.customer.basket.smoothies.count == 5 %>
      <% if  current_user.customer.first_name.nil?%>
        <%= link_to "CHECKOUT", new_customer_address_path(current_user.customer), class: 'btn-yoggie-main-green' %>
      <% else %>
        <%= link_to "CHECKOUT", new_customer_address_path(current_user.customer), class: 'btn-yoggie-main-green' %>
      <% end %>

      <% end %>
      <div class="our-smoothies">
        <% @smoothies.each do |smoothie| %>
          <%= render 'smoothies/card', smoothie: smoothie %>
        <% end %>
      </div>
    <% end %>
</div>
   <% if !current_user.customer.standard? %>
    <% if current_user.customer.basket.status == 'pending' && current_user.customer.basket.smoothies.count == 5 %>
        <div class="text-center">
          <%= link_to "CHECKOUT", new_customer_address_path(current_user.customer), class: 'btn-yoggie-main-green text-center' %>
        </div>
     <% end %>
     <div class="our-smoothies">
         <%= render 'smoothies/card_tailored', smoothies: @smoothies %>
      </div>
    <% end %>
<% else %>
  <div class="our-smoothies">
    <% @smoothies.each do |smoothie| %>
      <%= render 'smoothies/card_guest', smoothie: smoothie %>
    <% end %>
  </div>
<% end %>
<br></br>

<!-- new_customer_payment_path(current_user.customer) -->

app/views/smoothies/show.html.erb
<!-- <div class="smoothie-banner"></div> -->
<div class="smoothie-wrapper">
  <div class="smoothie">
    <div class="standard-yoggie-main section-padding">
      <div class="back-to-smoothies-link">
        <i class="fa fa-arrow-left"> </i> <%= link_to 'Back to all Yoggies', 'javascript:history.back()' %>
      </div>
      <h2><%= @smoothie.name.titleize %></h2>
      <div class="standard-yoggie-main-content">
        <%= cl_image_tag @smoothie.image, width: 300 %>
        <div class="standard-yoggie-main-details">
          <h4><%= @smoothie.description %><br></br></h4>
            <%#ß= link_to "ADD TO BOX", customer_baskets_path(@smoothie, current_user.customer), class: "btn-yoggie-main-clear"  %>
        </div>
      </div>
      <div class="badges">
        <% @smoothie.badges.each do |badge| %>
          <%= cl_image_tag badge.image %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="standard-yoggie-nutrition">
    <div class="nutrition-border section-padding">
      <div class="standard-yoggie-nutrition-top">
        <div class="standard-yoggie-nutrition-topleft">
          <h4>in the mix</h4>
          <div class="large-ingredients">
              <% @large_ingredients.each do |large_ingredient| %>
                <div>
                  <%= cl_image_tag(large_ingredient.image, width: 100, height: 100, crop: :fit, class: 'ingredient-img-small') %>
                  <% if large_ingredient.allergen? %>
                    <p><%= large_ingredient.name.titleize %><sup>&#10013;</sup></p>
                  <% else %>
                    <p><%= large_ingredient.name.titleize %></p>
                  <% end %>
                </div>
              <% end %>
          </div>
          <br>
          <h4>plus</h4>
          <ul class="no-style">
            <% @small_ingredients.each do |small_ingredient| %>
              <li>
                <% if small_ingredient.allergen? %>
                  ✓ &nbsp;<%= small_ingredient.name.titleize %><sup>&#10013;</sup>
                <% else %>
                  ✓ &nbsp;<%= small_ingredient.name.titleize %>
                <% end %>
              </li>
            <% end %>
          </ul>
          <br>
          <h4>superfood</h4>
          <ul class="no-style">
            <li>
              ✓ &nbsp;<%= @smoothie.superfood.titleize %>
            </li>
          </ul>
        </div>
        <div class="standard-yoggie-nutrition-right">
          <h4>why it's delicious</h4>
          <p><%= @smoothie.ingredient_description %></p>
          <br>
          <h4>benefits to you</h4>
          <ul>
            <% if @smoothie.benefits_one.present? %>
              <li><%= @smoothie.benefits_one %></li>
            <% end %>
            <% if @smoothie.benefits_two.present? %>
              <li><%= @smoothie.benefits_two %></li>
            <% end %>
            <% if @smoothie.benefits_three.present? %>
              <li><%= @smoothie.benefits_three %></li>
            <% end %>
          </ul>
          <br>
          <h4>tastes great with</h4>
          <p><%= @smoothie.great_with %></p>
        </div>
      </div>

      <div class="standard-yoggie-nutrition-bottom">
        <div class="js-tabs-container yoggie-single-tabs-container">
          <ul class="yoggie-single-tabs-list">
            <li class="filler-tab"></li>
            <li class="js-tab macro-tab tab--active" data-tab="macro"><h4>macros</h4></li>
            <li class="js-tab nutrition-tab" data-tab="nutrition"><h4>nutrition</h4></li>
            <li class="js-tab ingredients-tab" data-tab="ingredients"><h4>ingredients</h4></li>
            <li class="filler-tab"></li>
          </ul>
          <div class="js-tab-content tab-content--active yoggie-single-tab-content" data-tab="macro">
            <div class="yoggie-macro-tab">
              <% if current_user.try(:customer) %>
                <h4>your smoothie has...</h4>
              <% end %>

              <div class="macro-main center">
                <div class="macro-info-left">
                  <% if current_user.try(:customer) %>
                    <div class="info-focus"><%= current_user.customer.calories_per_shake %></div>
                    <div>kcal per yoggie</div>
                  <% else %>
                    <div class="info-focus"><%= @smoothie.nutri_info.energy_kcal %></div>
                    <div>kcal per 100g</div>
                  <% end %>
                </div>

                <ul class="macro-info-list">
                  <li class="green-border">
                    <div class="percentage"><%= @smoothie.nutri_info.protein_percentage %>%</div>
                    <div class="nutri">Protein</div>
                    <% if current_user.try(:customer) %>
                      <div class="grams">
                        <%= current_user.customer.calculate_tailored_stat(@smoothie, :protein_g).round %>g
                      </div>
                    <% else %>
                      <div class="grams half-circle"></div>
                    <% end %>
                  </li>
                  <li class="yellow-border">
                    <div class="percentage"><%= @smoothie.nutri_info.carbs_percentage %>%</div>
                    <div class="nutri">Carbs</div>
                    <% if current_user.try(:customer) %>
                      <div class="grams">
                        <%= current_user.customer.calculate_tailored_stat(@smoothie, :carbs_g).round %>g
                      </div>
                    <% else %>
                      <div class="grams half-circle"></div>
                    <% end %>
                  </li>
                  <li class="orange-border">
                    <div class="percentage"><%= @smoothie.nutri_info.fat_percentage %>%</div>
                    <div class="nutri">Fats</div>
                    <% if current_user.try(:customer) %>
                      <div class="grams">
                        <%= current_user.customer.calculate_tailored_stat(@smoothie, :fat_g).round %>g
                      </div>
                    <% else %>
                      <div class="grams half-circle"></div>
                    <% end %>
                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="js-tab-content yoggie-single-tab-content" data-tab="nutrition">
            <div class="nutrition-table-container">
              <table id="customers">
                <tbody>
                  <tr class="no-bottom-border">
                    <th>Typical values</th>
                    <th>per 100g</th>
                    <% if current_user.try(:customer) %>
                      <th>per yoggie pack</th>
                    <% end %>
                  </tr>
                  <tr>
                    <th>&nbsp;</th>
                    <th class="th-small-font"><i>frozen as supplied</i></th>
                    <% if current_user.try(:customer) %>
                      <th>&nbsp;</th>
                    <% end %>
                  </tr>
                  <tr class="no-bottom-border">
                    <td>Energy</td>
                    <td><%= @smoothie.nutri_info.energy_kJ.round %> kJ</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :energy_kJ).round %> kJ</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td>&nbsp;</td>
                    <td><%= @smoothie.nutri_info.energy_kcal.round %> kCal</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :energy_kcal).round %> kCal</td>
                    <% end %>
                  </tr>
                  <tr class="no-bottom-border">
                    <td>Fat</td>
                    <td><%= @smoothie.nutri_info.fat_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :fat_g).round %> g</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td>of which saturates</td>
                    <td><%= @smoothie.nutri_info.fat_saturates_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :fat_saturates_g).round %> g</td>
                    <% end %>
                  </tr>
                  <tr class="no-bottom-border">
                    <td>Carbohydrate</td>
                    <td><%= @smoothie.nutri_info.carbs_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :carbs_g).round %> g</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td>of which sugars</td>
                    <td><%= @smoothie.nutri_info.carbs_sugars_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :carbs_sugars_g).round %> g</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td>Fibre</td>
                    <td><%= @smoothie.nutri_info.fibre_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :fibre_g).round %> g</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td>Protein</td>
                    <td><%= @smoothie.nutri_info.protein_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :protein_g).round %> g</td>
                    <% end %>
                  </tr>
                  <tr>
                    <td>Salt</td>
                    <td><%= @smoothie.nutri_info.salt_g.round %> g</td>
                    <% if current_user.try(:customer) %>
                      <td><%= current_user.customer.calculate_tailored_stat(@smoothie, :salt_g).round %> g</td>
                    <% end %>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="js-tab-content yoggie-single-tab-content" data-tab="ingredients">
            <div class="ingredients-tab-content">
              <div class="row">
                <div class="col-xs-6">
                  <h4>Smoothie contains</h4>
                  <p>
                    <%= @smoothie.ingredients.uniq.map{|i| i.name.titleize}.join(", ") %>
                  </p>
                  <br>
                  <h4>Ingredients contain</h4>
                  <% @special_ingredients.each do |special_ingredient| %>
                    <p>
                      <strong>
                        <%= special_ingredient.name.titleize %>
                      </strong>
                    </p>
                    <p style="word-wrap: break-word;">
                      <%= special_ingredient.contents %>
                    </p>
                  <% end %>
                </div>
                <div class="col-xs-6">
                  <h4>Allergens</h4>
                  <p>
                    <strong>
                      For allergens see ingredients with symbol &#10013; and/or in bold text
                    </strong>
                  </p>
                  <p>
                    In addition to the above, due to the environment within our packaging facility, our packs may contain low levels of the following allergens: Cereals containing gluten; Crustaceans; Eggs; Fish; Peanuts; Soya; Milk; Nuts: almonds, hazelnuts, walnuts, cashews, pecan nuts, brazil nuts, pistachio nuts, macadamia nuts; Celery; Sesame; Sulphur dioxide and Sulphites; Lupin; Molluscs; Mustard.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      <br>
    </div>
  </div>
</div>