config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # get 'smoothies', to: 'pages#smoothies'
  get 'contact', to: 'pages#contact'
  get 'faqs', to: 'pages#faqs'
  get 'privacy', to: 'pages#privacy'
  get 'terms', to: 'pages#terms'
  get 'newsletter', to: 'pages#newsletter'
  get 'customer/choose_standard', to: 'customers#choose_standard', as: :choose_standard
  get 'customer/choose_custom', to: 'customers#choose_custom', as: :choose_custom
  get 'smoothies/:id', to: "smoothies#show", as: :smothie_page
  patch 'add_to_basket', to: 'baskets#add_to_basket', as: :add_to_basket
  patch 'update_newsletter', to: 'users#update_newsletter', as: :update_newsletter
  get 'my_nutrition/:basket_id', to: 'baskets#my_nutrition', as: :my_nutrition
  get 'update_subscription/:id', to: 'customers#update_subscription', as: :update_subscription
  get 'customers/:id/dashboard_edit', to: "customers#dashboard_edit", as: :dashboard_edit
  patch 'customers/:id/dashboard_update', to: "customers#dashboard_update", as: :dashboard_update
  get 'customers/:id/update_status', to: "customers#update_status", as: :update_status
  get 'blog', to: 'articles#index'
  get 'about', to: 'pages#about'
# basket - customers/:customer_id/baskets/:basket_id

  resources :articles, only: [:create, :new, :edit, :update]
  resources :users do
    get :postcode_checker, on: :member
    patch :postcode_result, on: :member
  end

  resources :customers do
    resources :baskets do
      patch :cancel_subscription, on: :member
      patch :pause_subscription, on: :member
    end
    resources :addresses
    resources :payments, only: [:new, :create]
  end

  get 'blog/:slug', to: "articles#show", as: :article_page

  resources :smoothies

  resources :newsletter_subscribers, only: [:create, :new]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development? || Rails.env.staging?
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_customer
  skip_before_action :authenticate_user!

  def new
    redirect_to new_customer_address_path if @customer.address.nil?
    @basket = @customer.basket
    @fee = @customer.tailored? ? Basket::SUBSCRIPTION_FEE[:tailored] : Basket::SUBSCRIPTION_FEE[:standard]
  end

  def create

    if @customer.stripe_id?
      customer = Stripe::Customer.retrieve(@customer.stripe_id)
    else
      customer = Stripe::Customer.create(
        source: params[:stripeToken],
        email:  params[:stripeEmail]
        )
    end

    subscription = Stripe::Subscription.create(
      customer: customer.id,
      plan: retrieve_plan_id
    )

    @customer.update(stripe_id: customer.id)

    if @customer.basket.status == 'active'
      cancel_previous_subscription
      AdminMailer.subscription_change(@customer).deliver_now
    else
      AdminMailer.new_order(@customer).deliver_now
    end

    @customer.basket.update(status: 'active', stripe_sub_id: subscription.id)
    CustomerMailer.order_confirmation(@customer).deliver_now
    flash[:notice] = "Thank you, your payment was successful."
    redirect_to customer_path(@customer)

  rescue Stripe::CardError => e
    flash[:alert] = "#{e.message} Please try again."
    redirect_to new_customer_payment_path(@customer)
  end

  protect_from_forgery

  private

  def retrieve_plan_id
    return 'plan_EKThXqZJTpyJIA' if @customer.basket.tailored?
    'plan_EKTiNGauVhaso5'
  end

  def cancel_previous_subscription
    subscription = Stripe::Subscription.retrieve(@customer.basket.stripe_sub_id)
    subscription.delete
  end

  def set_customer
    @customer = Customer.friendly.find(params[:customer_id])
  end
end

app/views/payments/new.html.erb
<div class="review-order-wrapper">
  <h3>Review Your Order</h3>
    <h4>Your <%= @customer.user.standard ? "bare" : "" %> yoggies</h4>
    <% @customer.basket.smoothies.group_by {|smoothie| smoothie.name}.each do |smoothie_array| %>
      <p><span> <%= smoothie_array[1].count %>  x   <%= smoothie_array[0].titleize %></span></p>
    <% end %>
    <!--<p>Total of <%= @customer.basket.smoothies.count %> smoothies </p>-->
    <%= link_to 'Change my order', smoothies_path(@customer, @customer.basket) %>
  </ul>
  <br>
  <h4>Weekly subscription </h4>
  <p>£<%= @fee /100 %></p>
  <br>
  <h4>Deliver to</h4>
  <p><%= @customer.first_name %> <%= @customer.last_name %></p>
  <p><%= @customer.address.address_line_one %></p>
  <p><%= @customer.address.address_line_two %></p>
  <p><%= @customer.address.address_line_three %></p>
  <p><%= UKPostcode.parse(@customer.address.postcode) %></p>
  <%= link_to 'Change my address', edit_customer_address_path(@customer, @customer.address) %>
  <br>
  <h4>Delivery details</h4>
  <p><strong>Email is:</strong><br><%= @customer.user.email %></p>
  <p><strong>Safe place: </strong><span><i class="fa fa-info" data-toggle="tooltip" data-placement="top" title="We will leave your frozen box in your Safe Place between 3am and 6am in the morning. Don't forget to put your packs in the freezer!"></i></span><br><%= @customer.address.delivery_instructions %></p>
  <p><strong>Delivery day:</strong> <br>Tuesday</p>
  <br>
  <h4>Other</h4>
    <div class="order-details">
    <p><strong>Box price:</strong> £<%= @fee / 100 %></p>
    <p><strong>Price per yoggie:</strong> £<%= @fee / 500.0 %>0</p>
    <p><strong>Delivery:</strong> Free</p>
  </div>
  <p class="text-center small-font"><input type="checkbox" id="terms"> I agree to the <%= link_to "Privacy Policy", privacy_path %> and <%= link_to "Terms & Conditions", terms_path %>. I know I’m signing up to recurring deliveries which I can cancel any time. </p>
  <p></p>
  <%= form_tag customer_payments_path(@customer) do %>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
      data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
      data-description="Weekly subscription"
      data-email="<%= @customer.user.email %>"
      data-amount="<%= @fee %>"
      data-currency="gbp"
      data-locale="auto"
      data-label="Place order"></script>
    <% end %>
    <br>
</div>
<br></br>
<script>


const terms = document.getElementById("terms");
const stripe = document.getElementsByClassName("stripe-button-el");
stripe[0].disabled=true

terms.addEventListener("click", (event) => {
  if (terms.checked) {
    stripe[0].disabled=false
  } else {
    stripe[0].disabled=true
  }

});
</script>